name: Portfolio
services:
  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - api
      - front

  front:
    build:
      context: .
      dockerfile: front.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front:/front
      - /front/node_modules
    command: ["npm", "run", "dev"]

  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./api:/api
    command: ["python", "main.py"]
    environment:
      - DEBUG=1
    env_file:
      - .env
