services:
  api:
    build:
      context: .
      command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    environment:
      - DEBUG=1

